---
name: version-check

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  version-check:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - name: Check version
        uses: Azure/terraform-azurerm-avm-template/.github/actions/version-check@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
